CREATE TABLE accountprofileejb (
    USERID VARCHAR(250) NOT NULL PRIMARY KEY,
    PASSWD VARCHAR(250),
    FULLNAME VARCHAR(250),
    ADDRESS VARCHAR(250),
    EMAIL VARCHAR(250),
    CREDITCARD VARCHAR(250)
);

CREATE TABLE accountejb (
    ACCOUNTID SERIAL PRIMARY KEY,
    LOGINCOUNT INTEGER NOT NULL DEFAULT 0,
    LOGOUTCOUNT INTEGER NOT NULL DEFAULT 0,
    LASTLOGIN TIMESTAMP,
    CREATIONDATE TIMESTAMP,
    BALANCE DECIMAL(14,2),
    OPENBALANCE DECIMAL(14,2),
    PROFILE_USERID VARCHAR(250) REFERENCES accountprofileejb(USERID)
);

CREATE TABLE quoteejb (
    SYMBOL VARCHAR(250) NOT NULL PRIMARY KEY,
    COMPANYNAME VARCHAR(250),
    VOLUME DOUBLE PRECISION NOT NULL DEFAULT 0,
    PRICE DECIMAL(14,2),
    OPEN1 DECIMAL(14,2),
    LOW DECIMAL(14,2),
    HIGH DECIMAL(14,2),
    CHANGE1 DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE holdingejb (
    HOLDINGID SERIAL PRIMARY KEY,
    QUANTITY DOUBLE PRECISION NOT NULL,
    PURCHASEPRICE DECIMAL(14,2),
    PURCHASEDATE TIMESTAMP,
    ACCOUNT_ACCOUNTID INTEGER REFERENCES accountejb(ACCOUNTID),
    QUOTE_SYMBOL VARCHAR(250) REFERENCES quoteejb(SYMBOL)
);

CREATE TABLE orderejb (
    ORDERID SERIAL PRIMARY KEY,
    ORDERTYPE VARCHAR(250),
    ORDERSTATUS VARCHAR(250),
    OPENDATE TIMESTAMP,
    COMPLETIONDATE TIMESTAMP,
    QUANTITY DOUBLE PRECISION NOT NULL,
    PRICE DECIMAL(14,2),
    ORDERFEE DECIMAL(14,2),
    ACCOUNT_ACCOUNTID INTEGER REFERENCES accountejb(ACCOUNTID),
    QUOTE_SYMBOL VARCHAR(250) REFERENCES quoteejb(SYMBOL),
    HOLDING_HOLDINGID INTEGER REFERENCES holdingejb(HOLDINGID)
);
